// options/modules/dom-refs.js — DOM element references for the options page
(function (global) {
    const FORM_FIELD_IDS = [
        "enable_select",
        "engine_select",
        "llm_engine_select",
        "translate_shortcut",
        "source_lang",
        "target_lang",
        "openai_api_url",
        "openai_api_key",
        "openai_model",
        "openai_custom_model",
        "openai_custom_prompt",
        "show_thoughts",
        "openai_reasoning_effort",
        "openai_max_completion_tokens",
        "custom_openai_api_url",
        "custom_openai_api_key",
        "custom_openai_model",
        "custom_openai_custom_model",
        "custom_openai_custom_prompt",
        "custom_openai_show_thoughts",
        "custom_openai_reasoning_effort",
        "custom_openai_max_completion_tokens",
        "openrouter_api_url",
        "openrouter_api_key",
        "openrouter_model",
        "openrouter_custom_model",
        "openrouter_custom_prompt",
        "openrouter_show_thoughts",
        "openrouter_reasoning_effort",
        "openrouter_max_completion_tokens",
        "deepseek_api_url",
        "deepseek_api_key",
        "deepseek_model",
        "deepseek_custom_model",
        "deepseek_custom_prompt",
        "deepseek_show_thoughts",
        "siliconflow_api_url",
        "siliconflow_api_key",
        "siliconflow_model",
        "siliconflow_custom_model",
        "siliconflow_custom_prompt",
        "siliconflow_show_thoughts",
        "qwen_api_url",
        "qwen_api_key",
        "qwen_model",
        "qwen_custom_model",
        "qwen_custom_prompt",
        "qwen_show_thoughts",
        "qwen_thinking_budget",
        "qwen_preserve_thinking",
        "glm_api_url",
        "glm_api_key",
        "glm_model",
        "glm_custom_model",
        "glm_custom_prompt",
        "glm_show_thoughts",
        "glm_clear_thinking",
        "xiaomi_api_url",
        "xiaomi_api_key",
        "xiaomi_model",
        "xiaomi_custom_model",
        "xiaomi_custom_prompt",
        "xiaomi_show_thoughts",
        "xiaomi_max_completion_tokens",
        "grok_api_url",
        "grok_api_key",
        "grok_model",
        "grok_custom_model",
        "grok_custom_prompt",
        "grok_show_thoughts",
        "nim_api_url",
        "nim_api_key",
        "nim_model",
        "nim_custom_model",
        "nim_custom_prompt",
        "nim_show_thoughts",
        "nim_max_tokens",
        "claude_api_url",
        "claude_api_key",
        "claude_model",
        "claude_custom_model",
        "claude_custom_prompt",
        "claude_show_thoughts",
        "claude_max_tokens",
        "claude_thinking_mode",
        "claude_thinking_budget",
        "claude_thinking_effort",
        "gemini_api_url",
        "gemini_api_key",
        "gemini_model",
        "gemini_custom_model",
        "gemini_custom_prompt",
        "gemini_show_thoughts",
        "gemini_thinking_level",
        "gemini_thinking_budget",
        "ollama_api_url",
        "ollama_model_select",
        "ollama_custom_model",
        "ollama_custom_prompt",
        "ollama_show_thoughts",
        "deepl_api_url",
        "deepl_api_key",
        "deeplx_api_url",
        "deeplx_api_key",
        "special_translate_provider",
        "special_translate_api_url",
        "special_translate_api_key",
        "special_translate_model_select",
        "special_translate_custom_model",
        "special_translate_custom_prompt",
        "special_translate_show_thoughts",
        "theme_mode",
        "font_family",
        "bubble_width_percent",
        "bubble_height_percent",
    ];

    const LLM_ENGINES = new Set([
        "openai",
        "custom_openai",
        "openrouter",
        "gemini",
        "claude",
        "qwen",
        "deepseek",
        "siliconflow",
        "glm",
        "xiaomi",
        "grok",
        "nim",
        "ollama",
    ]);

    function createDomRefs() {
        const els = {};
        FORM_FIELD_IDS.forEach((id) => (els[id] = document.getElementById(id)));

        const sections = {
            openai: document.getElementById("openai_section"),
            customOpenAI: document.getElementById("custom_openai_section"),
            openrouter: document.getElementById("openrouter_section"),
            deepseek: document.getElementById("deepseek_section"),
            siliconflow: document.getElementById("siliconflow_section"),
            qwen: document.getElementById("qwen_section"),
            glm: document.getElementById("glm_section"),
            xiaomi: document.getElementById("xiaomi_section"),
            grok: document.getElementById("grok_section"),
            nim: document.getElementById("nim_section"),
            claude: document.getElementById("claude_section"),
            gemini: document.getElementById("gemini_section"),
            ollama: document.getElementById("ollama_section"),
            deepl: document.getElementById("deepl_section"),
            deeplx: document.getElementById("deeplx_section"),
            specialTranslate: document.getElementById(
                "special_translate_section",
            ),
        };

        const engineSectionsById = new Map(
            [
                ["custom_openai_section", sections.customOpenAI],
                ["openrouter_section", sections.openrouter],
                ["deepseek_section", sections.deepseek],
                ["siliconflow_section", sections.siliconflow],
                ["qwen_section", sections.qwen],
                ["glm_section", sections.glm],
                ["xiaomi_section", sections.xiaomi],
                ["grok_section", sections.grok],
                ["nim_section", sections.nim],
                ["claude_section", sections.claude],
                ["gemini_section", sections.gemini],
                ["ollama_section", sections.ollama],
                ["deepl_section", sections.deepl],
                ["deeplx_section", sections.deeplx],
                ["special_translate_section", sections.specialTranslate],
            ].filter(([, el]) => el),
        );

        const glossary = {
            exportBtn: document.getElementById("glossary_export"),
            importBtn: document.getElementById("glossary_import"),
            importFileInput: document.getElementById("glossary_import_file"),
            statusEl: document.getElementById("glossary_status"),
            listEl: document.getElementById("glossary_list"),
            saveBtn: document.getElementById("glossary_save"),
            cancelEditBtn: document.getElementById("glossary_cancel_edit"),
            clearBtn: document.getElementById("glossary_clear"),
            sourceLangEl: document.getElementById("glossary_source_lang"),
            targetLangEl: document.getElementById("glossary_target_lang"),
            sourceTermEl: document.getElementById("glossary_source_term"),
            targetTermEl: document.getElementById("glossary_target_term"),
            caseSensitiveEl: document.getElementById("glossary_case_sensitive"),
            wholeWordEl: document.getElementById("glossary_whole_word"),
        };

        const history = {
            searchEl: document.getElementById("history_search"),
            filterEl: document.getElementById("history_filter"),
            refreshBtn: document.getElementById("history_refresh"),
            clearBtn: document.getElementById("history_clear"),
            listEl: document.getElementById("history_list"),
            statusEl: document.getElementById("history_status"),
        };

        const wizard = {
            toggleBtn: document.getElementById("setup_wizard_toggle"),
            panelEl: document.getElementById("setup_wizard_panel"),
            statusEl: document.getElementById("setup_wizard_status"),
        };

        const sync = {
            configExportBtn: document.getElementById("config_export"),
            configImportBtn: document.getElementById("config_import"),
            configImportFileInput: document.getElementById("config_import_file"),
            configStatusEl: document.getElementById("config_status"),
            webdavBaseUrlEl: document.getElementById("webdav_base_url"),
            webdavUsernameEl: document.getElementById("webdav_username"),
            webdavPasswordEl: document.getElementById("webdav_password"),
            webdavRemoteDirEl: document.getElementById("webdav_remote_dir"),
            webdavSaveLocalBtn: document.getElementById("webdav_save_local"),
            syncTestBtn: document.getElementById("sync_test"),
            syncUploadBtn: document.getElementById("sync_upload"),
            syncDownloadBtn: document.getElementById("sync_download"),
            syncBidirectionalBtn: document.getElementById("sync_bidirectional"),
            syncStatusEl: document.getElementById("sync_status"),
        };

        const pdf = {
            openLocalPdfBtn: document.getElementById("open_local_pdf"),
            currentPdfStatusEl: document.getElementById("current_pdf_status"),
        };

        return {
            els,
            sections,
            openaiSection: sections.openai,
            engineSectionsById,
            glossary,
            history,
            wizard,
            sync,
            pdf,
            LLM_ENGINES,
        };
    }

    global.JYT_OPTION_DOM = {
        createDomRefs,
        FORM_FIELD_IDS,
        LLM_ENGINES,
    };
})(globalThis);
