/**
 * Generates libs/i18n-messages.js and libs/i18n-messages.mjs from i18n/locales/*.json
 * Run: node scripts/build-i18n.mjs [--check]
 */
import { readdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const ROOT = resolve(".");
const LOCALES_DIR = resolve(ROOT, "i18n/locales");
const OUT_JS = resolve(ROOT, "libs/i18n-messages.js");
const OUT_MJS = resolve(ROOT, "libs/i18n-messages.mjs");

function stableStringify(value) {
    if (Array.isArray(value)) {
        return `[${value.map(stableStringify).join(",")}]`;
    }
    if (value && typeof value === "object") {
        return `{${Object.keys(value)
            .sort()
            .map(
                (key) =>
                    `${JSON.stringify(key)}:${stableStringify(value[key])}`,
            )
            .join(",")}}`;
    }
    return JSON.stringify(value);
}

async function loadLocales() {
    const files = (await readdir(LOCALES_DIR))
        .filter((name) => name.endsWith(".json"))
        .sort();
    const messages = {};
    for (const file of files) {
        const lang = file.replace(/\.json$/, "");
        const raw = await readFile(resolve(LOCALES_DIR, file), "utf8");
        messages[lang] = JSON.parse(raw);
    }
    return messages;
}

function buildJsOutput(messages) {
    return `// AUTO-GENERATED by scripts/build-i18n.mjs — do not edit by hand.
(function (global) {
    global.JYT_I18N_MESSAGES = ${stableStringify(messages)};
})(typeof globalThis !== "undefined" ? globalThis : window);
`;
}

function buildMjsOutput(messages) {
    return `// AUTO-GENERATED by scripts/build-i18n.mjs — do not edit by hand.
export const I18N_MESSAGES = ${stableStringify(messages)};
`;
}

async function main() {
    const checkOnly = process.argv.includes("--check");
    const messages = await loadLocales();
    const jsOut = buildJsOutput(messages);
    const mjsOut = buildMjsOutput(messages);

    if (checkOnly) {
        const [prevJs, prevMjs] = await Promise.all([
            readFile(OUT_JS, "utf8").catch(() => ""),
            readFile(OUT_MJS, "utf8").catch(() => ""),
        ]);
        if (prevJs !== jsOut || prevMjs !== mjsOut) {
            console.error(
                "i18n message bundles are out of date. Run: node scripts/build-i18n.mjs",
            );
            process.exit(1);
        }
        console.log("i18n message bundles are up to date");
        return;
    }

    await Promise.all([
        writeFile(OUT_JS, jsOut, "utf8"),
        writeFile(OUT_MJS, mjsOut, "utf8"),
    ]);
    console.log(`Updated ${OUT_JS}`);
    console.log(`Updated ${OUT_MJS}`);
}

await main();
