/**
 * Bundle content scripts into dist/content.bundle.js and dist/iframe-proxy.bundle.js.
 * Run: node scripts/build-content.mjs
 */
import { mkdir } from "node:fs/promises";
import { resolve } from "node:path";
import esbuild from "esbuild";

const ROOT = resolve(".");
const OUT_DIR = resolve(ROOT, "dist");

const SHARED_BUILD_OPTIONS = {
    bundle: true,
    format: "iife",
    platform: "browser",
    target: ["chrome109", "firefox140"],
    minify: false,
    keepNames: true,
    legalComments: "inline",
    banner: {
        js: "// AUTO-GENERATED by scripts/build-content.mjs — do not edit by hand.",
    },
    logLevel: "info",
};

await mkdir(OUT_DIR, { recursive: true });

const contentOutFile = resolve(OUT_DIR, "content.bundle.js");
await esbuild.build({
    ...SHARED_BUILD_OPTIONS,
    entryPoints: [resolve(ROOT, "content/entry.js")],
    outfile: contentOutFile,
    loader: {
        ".css": "text",
    },
});
console.log(`Built ${contentOutFile}`);

const proxyOutFile = resolve(OUT_DIR, "iframe-proxy.bundle.js");
await esbuild.build({
    ...SHARED_BUILD_OPTIONS,
    entryPoints: [resolve(ROOT, "content/iframe-proxy.js")],
    outfile: proxyOutFile,
});
console.log(`Built ${proxyOutFile}`);
