/**
 * Bundle content script modules into dist/content.bundle.js (no minification).
 * Run: node scripts/build-content.mjs
 */
import { mkdir } from "node:fs/promises";
import { resolve } from "node:path";
import esbuild from "esbuild";

const ROOT = resolve(".");
const OUT_DIR = resolve(ROOT, "dist");
const OUT_FILE = resolve(OUT_DIR, "content.bundle.js");

await mkdir(OUT_DIR, { recursive: true });

await esbuild.build({
    entryPoints: [resolve(ROOT, "content/entry.js")],
    outfile: OUT_FILE,
    bundle: true,
    format: "iife",
    platform: "browser",
    target: ["chrome109", "firefox140"],
    minify: false,
    keepNames: true,
    legalComments: "inline",
    banner: {
        js: "// AUTO-GENERATED by scripts/build-content.mjs — do not edit by hand.",
    },
    logLevel: "info",
});

console.log(`Built ${OUT_FILE}`);
