(function (global) {
    const DEFAULT_SETTINGS = {
        enabled: "on",
        engine: "auto",
        llm_engine: "openai",
        translate_shortcut: "",
        source_lang: "auto",
        target_lang: "auto",
        openai_api_url: "",
        openai_api_key: "",
        openai_model: "gpt-5.4-mini",
        openai_custom_model: "",
        openai_custom_prompt: "",
        openai_thinking_model: "gpt-5-thinking",
        show_thoughts: false,
        openai_reasoning_effort: "medium",
        openai_max_completion_tokens: 0,
        custom_openai_api_url: "https://api.openai.com/v1/chat/completions",
        custom_openai_api_key: "",
        custom_openai_model: "gpt-4o-mini",
        custom_openai_custom_model: "",
        custom_openai_custom_prompt: "",
        custom_openai_show_thoughts: false,
        custom_openai_reasoning_effort: "medium",
        custom_openai_max_completion_tokens: 0,
        openrouter_api_url: "https://openrouter.ai/api/v1/chat/completions",
        openrouter_api_key: "",
        openrouter_model: "openrouter/free",
        openrouter_custom_model: "",
        openrouter_custom_prompt: "",
        openrouter_show_thoughts: false,
        openrouter_reasoning_effort: "medium",
        openrouter_max_completion_tokens: 0,
        deepseek_api_url: "https://api.deepseek.com/chat/completions",
        deepseek_api_key: "",
        deepseek_model: "deepseek-v4-flash",
        deepseek_custom_model: "",
        deepseek_custom_prompt: "",
        deepseek_show_thoughts: false,
        qwen_api_url:
            "https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation",
        qwen_api_key: "",
        qwen_model: "qwen3.5-plus",
        qwen_custom_model: "",
        qwen_custom_prompt: "",
        qwen_show_thoughts: false,
        qwen_thinking_budget: 0,
        qwen_preserve_thinking: false,
        glm_api_url: "https://open.bigmodel.cn/api/paas/v4/chat/completions",
        glm_api_key: "",
        glm_model: "glm-5.1",
        glm_custom_model: "",
        glm_custom_prompt: "",
        glm_show_thoughts: false,
        glm_clear_thinking: true,
        xiaomi_api_url: "https://api.xiaomimimo.com/v1/chat/completions",
        xiaomi_api_key: "",
        xiaomi_model: "mimo-v2.5",
        xiaomi_custom_model: "",
        xiaomi_custom_prompt: "",
        xiaomi_show_thoughts: false,
        xiaomi_max_completion_tokens: 0,
        grok_api_url: "https://api.x.ai/v1/chat/completions",
        grok_api_key: "",
        grok_model: "grok-4.3",
        grok_custom_model: "",
        grok_custom_prompt: "",
        grok_show_thoughts: false,
        claude_api_url: "https://api.anthropic.com/v1/messages",
        claude_api_key: "",
        claude_model: "claude-sonnet-4-6",
        claude_custom_model: "",
        claude_custom_prompt: "",
        claude_show_thoughts: false,
        claude_max_tokens: 4096,
        claude_thinking_mode: "adaptive",
        claude_thinking_budget: 2048,
        claude_thinking_effort: "medium",
        gemini_api_url:
            "https://generativelanguage.googleapis.com/v1beta/models",
        gemini_api_key: "",
        gemini_model: "gemini-flash-latest",
        gemini_custom_model: "",
        gemini_custom_prompt: "",
        gemini_show_thoughts: false,
        gemini_thinking_level: "high",
        gemini_thinking_budget: -1,
        ollama_api_url: "http://localhost:11434/api/chat",
        ollama_model: "qwen3.5:latest",
        ollama_custom_model: "",
        ollama_custom_prompt: "",
        ollama_show_thoughts: false,
        special_translate_provider: "ollama",
        special_translate_api_url: "http://localhost:11434/api/chat",
        special_translate_api_key: "",
        special_translate_model: "translategemma",
        special_translate_custom_model: "",
        special_translate_custom_prompt: "",
        special_translate_show_thoughts: false,
        theme_mode: "auto",
        font_family: "",
        bubble_width_percent: 20,
        bubble_height_percent: 40,
        glossary_enabled: true,
        glossary_terms: [],
        glossary_version: 1,
        config_updated_at: 0,
    };

    const MESSAGE_TYPES = {
        TRANSLATE_START: "TRANSLATE_START",
        TRANSLATE_CANCEL: "TRANSLATE_CANCEL",
        OLLAMA_GET_MODELS: "OLLAMA_GET_MODELS",
        OPENAI_COMPAT_GET_MODELS: "OPENAI_COMPAT_GET_MODELS",
        OPENROUTER_GET_MODELS: "OPENROUTER_GET_MODELS",
        CLAUDE_GET_MODELS: "CLAUDE_GET_MODELS",
        GEMINI_GET_MODELS: "GEMINI_GET_MODELS",
        SPECIAL_TRANSLATE_GET_MODELS: "SPECIAL_TRANSLATE_GET_MODELS",
        TERM_UPSERT: "TERM_UPSERT",
        TERM_IMPORT: "TERM_IMPORT",
        TERM_EXPORT: "TERM_EXPORT",
        TERM_LIST: "TERM_LIST",
        TERM_DELETE: "TERM_DELETE",
        TERM_CLEAR: "TERM_CLEAR",
        CONFIG_EXPORT: "CONFIG_EXPORT",
        CONFIG_IMPORT: "CONFIG_IMPORT",
        SYNC_TEST: "SYNC_TEST",
        SYNC_UPLOAD: "SYNC_UPLOAD",
        SYNC_DOWNLOAD: "SYNC_DOWNLOAD",
        SYNC_BIDIRECTIONAL: "SYNC_BIDIRECTIONAL",
        PDF_CHECK_URL: "PDF_CHECK_URL",
        PDF_OPEN_IN_VIEWER: "PDF_OPEN_IN_VIEWER",
        PDF_PROMPT_OFFER: "PDF_PROMPT_OFFER",
        PDF_PROMPT_VERDICT: "PDF_PROMPT_VERDICT",
        PDF_PROMPT_DECISION: "PDF_PROMPT_DECISION",
        PDF_GET_PENDING_PROMPT: "PDF_GET_PENDING_PROMPT",
    };

    global.JYT_SHARED = {
        DEFAULT_SETTINGS,
        MESSAGE_TYPES,
    };
})(typeof globalThis !== "undefined" ? globalThis : window);
